apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmqproducer
spec:
  selector:
    matchLabels:
      app: rabbitmqproducer
  template:
    metadata:
      labels:
        app: rabbitmqproducer
    spec:
      containers:
      - name: rabbitmqproducer
        image: saguhildon/rabbitmqproducerapi:1.1.0
        env:
        - name: RABBITMQ_HOST
          value: "rabbitmq"
        - name: RABBITMQ_PORT
          value: "5672"
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmqproducer
spec:
  type: NodePort
  selector:
    app: rabbitmqproducer
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 31500

